import type { Metadata } from "next";
import "./globals.css";
import { RMCHeader } from "@/components/custom/RMCHeader";
import { IType } from "@/types/menu";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >

          <RMCHeader menuList={[{ name: 'Blog', url: '/blog', children: [], type: IType.DATA }, { name: 'Peace of room', url: '/room', isTop: true }]} />
          {children}
      </body>
    </html>
  );
}
